export type FlexMargin = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl'
export type FlexPosition = 'relative' | 'absolute'
export type FlexHeight = 'sm' | 'md'
export type FlexStyle = 'link' | 'primary' | 'secondary'
export type FlexGravity = 'top' | 'bottom' | 'center'
export type FlexSize =
  | 'xxs'
  | 'xs'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | 'xxl'
  | '3xl'
  | '4xl'
  | '5xl'
export type FlexWeight = 'regular' | 'bold'
export type FlexTextStyle = 'normal' | 'italic'
export type FlexDecoration = 'none' | 'underline' | 'line-through'
export type FlexAlign = 'start' | 'end' | 'center'
